### ISSUE TITLE
`books` directory not created

### ISSUE THREAD

**Issue by lnxd** [vogler/blinkist-downloader#1]
Hi,

First off, great project! I wish this existed 6 weeks ago, but I'm glad I came across it tonight. Thank you for making it.

Just submitting a potential bug report. I'm running the script on macOS Sonoma 14.5 with Node.js v22.3.0, in iTerm with Full Disk Permissions.

If the `books` directory doesn't exist when it tries to create the database, it gives an error. I was able to resolve this by creating the directory before running the script for the first time.

I haven't properly reviewed the code, but if I get a chance over the next few days I'll take a look.

```
locator.innerText: Timeout 30000ms exceeded.
Call log:

    waiting for locator('a[data-test-id="book-card"]').nth(16).locator('div.text-mid-grey.text-caption.mt-2').last()

    at updateLibrary (/Users/lnxd/Working/blinkist-downloader/index.ts:70:84)
    at <anonymous> (/Users/lnxd/Working/blinkist-downloader/index.ts:228:5) {
    name: 'TimeoutError'
    }
    node
    /fs/promises:641
    return new FileHandle(await PromisePrototypeThen(
    ^

Error: ENOENT: no such file or directory, open 'books/.db.json.tmp'
at async open (node
/fs/promises:641:25)
at async writeFile (node
/fs/promises:1224:14)
at async #write (file:///Users/lnxd/Working/blinkist-downloader/node_modules/steno/lib/index.js:53:13)
at async Low.write (file:///Users/lnxd/Working/blinkist-downloader/node_modules/lowdb/lib/core/Low.js:22:13)
at <anonymous> (/Users/lnxd/Working/blinkist-downloader/index.ts:239:3) {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: 'books/.db.json.tmp'
}
```

There was a second issue I was able to get around by adding some quick error handling to skip certain books that were missing an element. Just noting this here to remind myself.

**Comment by vogler** [comment]
> If the books directory doesn't exist when it tries to create the database, it gives an error.

Thanks! Fixed. Thought lowdb does this. 

> There was a second issue I was able to get around by adding some quick error handling to skip certain books that were missing an element.

Do you still have the log? I also encountered some books that had elements missing or were a 404, but I thought I handled them all.
It also happened that it got stuck after some time on a request but then worked fine after a restart - not sure if they have some kind of rate limit or if it was a Playwright issue.
Thought about using https://github.com/Effect-TS/effect for retry etc. but it happened so rarely that I thought it wouldn't be worth it.
